Repository AdrienWehrle/earthspy, pull requests merged in 2024-12, with the labels that each got.

#108 Enable pre-commit and add action
  .github/workflows/main.yml
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  README.org
  docs/_build/html/_static/alabaster.css
  docs/_build/html/_static/basic.css
  docs/_build/html/_static/documentation_options.js
  docs/_build/html/_static/language_data.js
  docs/_build/html/_static/pygments.css
  docs/_build/html/_static/underscore.js
  docs/_build/html/genindex.html
  docs/_build/html/index.html
  docs/_build/html/search.html
  docs/_build/html/searchindex.js
  docs/api.rst
  docs/generated/earthspy.rst
  docs/index.rst
  earthspy/__init__.py
  earthspy/earthspy.py
  earthspy/operational/earthspy_NRT.py
  setup.py
  tests/__init__.py
  tests/test_earthspy.py
Labels: enhancement

#110 Add dependabot
  .github/dependabot.yml
Labels: enhancement

#114 Fix doc requirements
  .readthedocs.yml
  dev-environment.yml
  environment.yml
  requirements-dev.txt
Labels: bug

#116 Translate README and CONTRIBUTING to markdown
  CONTRIBUTING.md
  CONTRIBUTING.org
  README.md
Labels: documentation

#107 Test Geojson file fields
  .github/workflows/main.yml
  tests/test_earthspy.py
Labels: enhancement
